apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-verify
  # namespace: kube-verify

spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-verify
  template:
    metadata:
      labels:
        app: kube-verify
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
