apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  # claimRef:
      # name: my-claim
      # namespace: foo
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  # hostPath: # local storage
  #   path: /tmp/data
  gcePersistentDisk:
    pdName: bucket-disk
    fsType: ext4
