apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/rewrite-target: /

  name: kube-verify-ingress
  # namespace: kube-verify
spec:
  rules:
  - host: ranchertest.tk
    http:
      paths:
      - backend:
          serviceName: kube-verify
          servicePort: 8081
        path: /
  tls: # < placing a host in the TLS config will indicate a certificate should be created
  - hosts:
      - ranchertest.tk
      - www.ranchertest.tk
    secretName: ranchertest-tk-tls # < cert-manager will store the created certificate in this secret.

