apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/rewrite-target: /

  name: kube-verify-ingress
  # namespace: kube-verify
spec:
  rules:
  - host: lab.ranchertest.tk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-verify
            port:
              number: 8081

  tls: # < placing a host in the TLS config will indicate a certificate should be created
  - hosts:
      # - ranchertest.tk
      # - www.ranchertest.tk
      - lab.ranchertest.tk
    secretName: ranchertest-tk-tls # < cert-manager will store the created certificate in this secret.

