apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # To use ingress controller, add the kubernetes.io/ingress.class: nginx annotation to your Ingress resources.
    kubernetes.io/ingress.class: nginx
    # add an annotation indicating the issuer to use.
    # cert-manager.io/issuer: "letsencrypt-staging"

    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/rewrite-target: /

  name: kube-verify-ingress
  # namespace: kube-verify
  
spec:
  # ingressClassName: nginx
  rules:
  - host: ranchertest.tk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-verify
            port:
              number: 80
  - host: www.ranchertest.tk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-verify
            port:
              number: 80


  tls:
  - hosts:
      - ranchertest.tk
      - www.ranchertest.tk
    secretName: ranchertest-tk-tls # < cert-manager will store the created certificate in this secret.

